version: "3.8"

services:
  storage:
    container_name: postgres_container
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .ignored/pg-env.list
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .ignored/pgadmin-env.list
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${SERVER_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
